const mongoose = require("mongoose");

const facultyProfileSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, unique: true },
    employeeId: { type: String, trim: true },
    phone: { type: String, trim: true },
    qualification: { type: String, trim: true },
    areaOfExpertise: [{ type: String, trim: true }],
    googleScholarId: { type: String, trim: true },
    orcidId: { type: String, trim: true },
    scopusId: { type: String, trim: true },
    researchInterests: [{ type: String, trim: true }],
    profilePhotoUrl: { type: String, trim: true },
    bio: { type: String, trim: true },
    joinedAt: Date,
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

facultyProfileSchema.virtual("autoGeneratedResearchProfile").get(function profileText() {
  const interests = this.researchInterests?.length ? this.researchInterests.join(", ") : "Not specified";
  const expertise = this.areaOfExpertise?.length ? this.areaOfExpertise.join(", ") : "Not specified";
  return `Expertise: ${expertise}. Research interests: ${interests}.`;
});

facultyProfileSchema.virtual("profileImageUrl").get(function profileImageUrl() {
  return this.profilePhotoUrl || "";
});

module.exports = mongoose.model("FacultyProfile", facultyProfileSchema);
