export const roleLabels = {
  super_admin: "Super Admin",
  admin: "Admin",
  hod_dean: "HOD/Dean",
  faculty: "Faculty",
  research_coordinator: "Research Coordinator",
};

export const moduleConfig = {
  publications: {
    label: "Publications",
    endpoint: "publications",
    fileField: "document",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: ["journal", "conference", "book", "book_chapter", "article"],
        required: true,
      },
      { name: "authors", label: "Authors (comma separated)", type: "text" },
      { name: "journalOrConferenceName", label: "Journal/Conference", type: "text", required: true },
      { name: "doi", label: "DOI", type: "text" },
      { name: "issnIsbn", label: "ISSN/ISBN", type: "text" },
      { name: "publicationYear", label: "Publication Year", type: "number", required: true },
      {
        name: "indexingType",
        label: "Indexing Type",
        type: "select",
        options: ["Scopus", "SCI", "UGC Care", "IEEE", "Web of Science", "Other"],
      },
      { name: "impactFactor", label: "Impact Factor", type: "number" },
      { name: "citationCount", label: "Citation Count", type: "number" },
      { name: "file", label: "Upload Document", type: "file" },
    ],
    columns: ["title", "type", "publicationYear", "indexingType", "approvalStatus"],
  },
  projects: {
    label: "Research Projects",
    endpoint: "projects",
    fileField: "document",
    fields: [
      { name: "projectTitle", label: "Project Title", type: "text", required: true },
      { name: "fundingAgency", label: "Funding Agency", type: "text", required: true },
      { name: "principalInvestigator", label: "Principal Investigator", type: "text", required: true },
      { name: "coInvestigators", label: "Co-investigators (comma separated)", type: "text" },
      { name: "amountSanctioned", label: "Amount Sanctioned", type: "number" },
      { name: "startDate", label: "Start Date", type: "date" },
      { name: "endDate", label: "End Date", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["Proposed", "Ongoing", "Completed"] },
      { name: "progressReport", label: "Progress Report", type: "text" },
      { name: "file", label: "Upload Document", type: "file" },
    ],
    columns: ["projectTitle", "fundingAgency", "status", "amountSanctioned", "approvalStatus"],
  },
  patents: {
    label: "Patents",
    endpoint: "patents",
    fileField: "certificate",
    fields: [
      { name: "patentTitle", label: "Patent Title", type: "text", required: true },
      { name: "applicationNumber", label: "Application Number", type: "text", required: true },
      { name: "inventors", label: "Inventors (comma separated)", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["Filed", "Published", "Granted"] },
      { name: "filingDate", label: "Filing Date", type: "date" },
      { name: "grantDate", label: "Grant Date", type: "date" },
      { name: "file", label: "Upload Certificate", type: "file" },
    ],
    columns: ["patentTitle", "applicationNumber", "status", "filingDate", "approvalStatus"],
  },
  grants: {
    label: "Grants & Funding",
    endpoint: "grants",
    fileField: "document",
    fields: [
      { name: "grantProposal", label: "Grant Proposal", type: "text", required: true },
      { name: "agencyName", label: "Agency Name", type: "text", required: true },
      { name: "amountRequested", label: "Amount Requested", type: "number", required: true },
      { name: "amountApproved", label: "Amount Approved", type: "number" },
      { name: "utilizationReport", label: "Utilization Report", type: "text" },
      { name: "statusTracking", label: "Status Tracking", type: "text" },
      { name: "file", label: "Upload Document", type: "file" },
    ],
    columns: ["grantProposal", "agencyName", "amountRequested", "amountApproved", "approvalStatus"],
  },
  events: {
    label: "Conference/Seminar/FDP/Workshop",
    endpoint: "events",
    fileField: "certificate",
    fields: [
      { name: "eventName", label: "Event Name", type: "text", required: true },
      { name: "eventType", label: "Type", type: "select", options: ["Conference", "Seminar", "FDP", "Workshop"] },
      { name: "participationType", label: "Organized/Attended", type: "select", options: ["Organized", "Attended"] },
      { name: "role", label: "Role", type: "select", options: ["Participant", "Speaker", "Organizer"] },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "file", label: "Upload Certificate", type: "file" },
    ],
    columns: ["eventName", "eventType", "participationType", "role", "approvalStatus"],
  },
};
