import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import api from "../api/client";
import ProfileAvatar from "../components/ui/ProfileAvatar";
import { roleLabels } from "../config";

const FacultyProfilePage = () => {
  const [profile, setProfile] = useState(null);
  const [form, setForm] = useState({
    employeeId: "",
    qualification: "",
    areaOfExpertise: "",
    googleScholarId: "",
    orcidId: "",
    scopusId: "",
    researchInterests: "",
    bio: "",
  });
  const [photo, setPhoto] = useState(null);

  const loadProfile = async () => {
    try {
      const { data } = await api.get("/faculty/me");
      const p = data.data;
      setProfile(p);
      setForm({
        employeeId: p.employeeId || "",
        qualification: p.qualification || "",
        areaOfExpertise: (p.areaOfExpertise || []).join(", "),
        googleScholarId: p.googleScholarId || "",
        orcidId: p.orcidId || "",
        scopusId: p.scopusId || "",
        researchInterests: (p.researchInterests || []).join(", "),
        bio: p.bio || "",
      });
    } catch (_error) {
      setProfile(null);
    }
  };

  useEffect(() => {
    loadProfile();
  }, []);

  const saveProfile = async (e) => {
    e.preventDefault();

    const payload = new FormData();
    payload.append("employeeId", form.employeeId);
    payload.append("qualification", form.qualification);
    payload.append("areaOfExpertise", form.areaOfExpertise.split(",").map((x) => x.trim()));
    payload.append("googleScholarId", form.googleScholarId);
    payload.append("orcidId", form.orcidId);
    payload.append("scopusId", form.scopusId);
    payload.append("researchInterests", form.researchInterests.split(",").map((x) => x.trim()));
    payload.append("bio", form.bio);
    if (photo) payload.append("profilePhoto", photo);

    try {
      await api.put("/faculty/me", payload);
      toast.success("Profile updated");
      loadProfile();
    } catch (error) {
      toast.error(error.response?.data?.message || "Failed to update profile");
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900 md:flex-row md:items-center">
        <ProfileAvatar
          name={profile?.user?.name}
          photoUrl={profile?.profilePhotoUrl || profile?.profileImageUrl}
          className="h-20 w-20 shrink-0"
          textClassName="text-lg"
        />
        <div className="min-w-0">
          <h2 className="truncate text-xl font-semibold text-slate-900 dark:text-slate-100">Faculty Profile</h2>
          <p className="truncate text-sm text-slate-500 dark:text-slate-400">{profile?.user?.name || "No profile loaded"}</p>
          <p className="truncate text-sm text-slate-500 dark:text-slate-400">{profile?.user?.email || "-"}</p>
          <p className="truncate text-xs font-medium uppercase tracking-[0.2em] text-brand-700 dark:text-brand-300">
            {roleLabels[profile?.user?.role] || profile?.user?.role || "-"}
          </p>
        </div>
      </div>

      <form className="grid grid-cols-1 gap-4 md:grid-cols-2" onSubmit={saveProfile}>
        {Object.entries(form).map(([key, value]) => (
          <div key={key} className={key === "bio" ? "md:col-span-2" : ""}>
            <label className="mb-1 block text-sm font-medium capitalize">{key.replace(/([A-Z])/g, " $1")}</label>
            {key === "bio" ? (
              <textarea
                className="w-full rounded-lg border px-3 py-2"
                rows={3}
                value={value}
                onChange={(e) => setForm((prev) => ({ ...prev, [key]: e.target.value }))}
              />
            ) : (
              <input
                className="w-full rounded-lg border px-3 py-2"
                value={value}
                onChange={(e) => setForm((prev) => ({ ...prev, [key]: e.target.value }))}
              />
            )}
          </div>
        ))}

        <div className="md:col-span-2">
          <label className="mb-1 block text-sm font-medium">Profile Photo</label>
          <input type="file" className="w-full rounded-lg border px-3 py-2" onChange={(e) => setPhoto(e.target.files?.[0] || null)} />
        </div>

        <div className="md:col-span-2">
          <button className="rounded-lg bg-brand-600 px-4 py-2 text-white">Save Profile</button>
        </div>
      </form>

      {profile?.autoGeneratedResearchProfile ? (
        <div className="rounded-lg bg-brand-50 p-4 text-sm text-brand-700">
          <p className="font-medium">Auto-generated Faculty Research Profile</p>
          <p>{profile.autoGeneratedResearchProfile}</p>
        </div>
      ) : null}
    </div>
  );
};

export default FacultyProfilePage;
