import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import api from "../api/client";
import { toBackendFileUrl } from "../config/api";
import { useAuth } from "../context/AuthContext";

const reportTypes = [
  { value: "faculty_wise", label: "Faculty-wise Report" },
  { value: "department_wise", label: "Department-wise Report" },
  { value: "year_wise", label: "Year-wise Report" },
  { value: "naac", label: "NAAC Criterion III" },
  { value: "nba", label: "NBA Research Report" },
  { value: "nirf", label: "NIRF Research Output Report" },
  { value: "api_score", label: "API Score Report" },
  { value: "faculty_api_score", label: "Faculty API Score Report" },
];

const ReportsPage = () => {
  const { user } = useAuth();
  const [form, setForm] = useState({ type: "faculty_wise", format: "pdf", year: "" });
  const [reports, setReports] = useState([]);
  const [generating, setGenerating] = useState(false);
  const isFaculty = user?.role === "faculty";
  const availableTypes = isFaculty
    ? reportTypes.filter((type) => ["faculty_wise", "year_wise", "api_score", "faculty_api_score"].includes(type.value))
    : reportTypes;

  const loadReports = async () => {
    try {
      const { data } = await api.get("/reports");
      setReports(data.data || []);
    } catch (_error) {
      setReports([]);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const generateReport = async (e) => {
    e.preventDefault();
    setGenerating(true);
    try {
      await api.post("/reports/generate", {
        type: form.type,
        format: form.format,
        filters: form.year ? { year: form.year } : {},
      });
      toast.success("Report generated");
      loadReports();
    } catch (error) {
      toast.error(error.response?.data?.message || "Generation failed");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold">Reports</h2>
        <p className="text-sm text-slate-500">Generate PDF/Excel for NAAC, NBA, NIRF and internal analysis</p>
      </div>

      <form className="grid gap-3 rounded-xl border p-4 md:grid-cols-4" onSubmit={generateReport}>
        <select className="rounded-lg border px-3 py-2" value={form.type} onChange={(e) => setForm((p) => ({ ...p, type: e.target.value }))}>
          {availableTypes.map((item) => (
            <option key={item.value} value={item.value}>
              {item.label}
            </option>
          ))}
        </select>

        <select className="rounded-lg border px-3 py-2" value={form.format} onChange={(e) => setForm((p) => ({ ...p, format: e.target.value }))}>
          <option value="pdf">PDF</option>
          <option value="excel">Excel</option>
        </select>

        <input
          type="number"
          placeholder="Year (optional)"
          className="rounded-lg border px-3 py-2"
          value={form.year}
          onChange={(e) => setForm((p) => ({ ...p, year: e.target.value }))}
        />

        <button className="rounded-lg bg-brand-600 px-4 py-2 text-white disabled:opacity-70" disabled={generating}>
          {generating ? "Generating..." : "Generate"}
        </button>
      </form>

      {isFaculty ? (
        <p className="text-xs text-slate-500">Faculty can generate personal faculty-wise, year-wise, and API score reports.</p>
      ) : null}

      <div className="overflow-x-auto">
        <table className="min-w-full text-sm">
          <thead>
            <tr className="border-b text-left text-slate-600">
              <th className="py-2">Type</th>
              <th>Format</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Download</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report._id} className="border-b">
                <td className="py-2">{report.type}</td>
                <td>{report.format}</td>
                <td>{report.generatedBy?.name || "-"}</td>
                <td>{new Date(report.createdAt).toLocaleString()}</td>
                <td>
                  <a
                    className="text-brand-700 underline"
                    href={toBackendFileUrl(report.filePath)}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Open
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default ReportsPage;
